Pig Stack Trace
---------------
ERROR 6000: <file flatten.pig, line 4, column 0> Output Location Validation Failed for: 'file:///Users/liju_john01/Documents/gitprojects/pig/output More info to follow:
Output directory file:/Users/liju_john01/Documents/gitprojects/pig/output already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: <file flatten.pig, line 4, column 0> Output Location Validation Failed for: 'file:///Users/liju_john01/Documents/gitprojects/pig/output More info to follow:
Output directory file:/Users/liju_john01/Documents/gitprojects/pig/output already exists
	at org.apache.pig.newplan.logical.visitor.InputOutputFileValidatorVisitor.visit(InputOutputFileValidatorVisitor.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:84)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
	at org.apache.pig.newplan.logical.relational.LogicalPlan.validate(LogicalPlan.java:215)
	at org.apache.pig.PigServer$Graph.compile(PigServer.java:1852)
	at org.apache.pig.PigServer$Graph.access$300(PigServer.java:1528)
	at org.apache.pig.PigServer.execute(PigServer.java:1441)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:489)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:472)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:171)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:234)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:205)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:81)
	at org.apache.pig.Main.run(Main.java:630)
	at org.apache.pig.Main.main(Main.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory file:/Users/liju_john01/Documents/gitprojects/pig/output already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
	at org.apache.pig.newplan.logical.visitor.InputOutputFileValidatorVisitor.visit(InputOutputFileValidatorVisitor.java:69)
	... 25 more
================================================================================
